services:
  backend:
    build: ./mythic_backend
    env_file: .env
    container_name: mythic-backend
    volumes:
      - ./mythic_backend/data:/usr/src/app/data
      - ./mythic_backend/app:/usr/src/app/app
    ports:
      - "8001:8000"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    networks:
      - mythic-network

  frontend:
    build: ./mythic_frontend
    container_name: mythic-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:8001
    restart: unless-stopped
    networks:
      - mythic-network

networks:
  mythic-network:
    driver: bridge
